attempt1
tbilous/r_scholl_addon pull request #1
Opened 2017-05-24 19:15 UTC by tbilous

2017-05-25 14:08 UTC, index01d requested changes

2017-05-25 14:08 UTC, index01d commented on server.js
> +var express = require('express');
а этот файл зачем?:)

2017-05-25 14:08 UTC, index01d commented on server.js
> +var express = require('express');
нужно совместить все в один сервер, static можно подключать там же, где обрабатывается серверный рендеринг

2017-05-25 20:59 UTC, tbilous commented on server.js
> +var express = require('express');
Скаффолд валялся для для этой книжки "maxfarseer.gitbooks.io/react-course-ru/content/". Его взял, потому, что там те-же депенденсы. А этот файлик удалить забыл.

2017-05-26 14:42 UTC, index01d requested changes

2017-05-26 14:42 UTC, index01d commented on components/ui/BlogItem.js
> +  DOM.ul(
ul вроде как корневой элемент списка, ему бы наоборот лучше быть в BlogList

2017-05-26 15:04 UTC, tbilous commented on components/ui/BlogItem.js
> +  DOM.ul(
Можно и туда, конечно но он обертка для одного поста

2017-05-26 15:32 UTC, index01d commented on components/ui/BlogItem.js
> +  DOM.ul(
Не понимаю пока что. Насколько я определяю должны быть компоненты: Список записей и Одна запись. В списке должны итерироваться записи и отображаться в некотором элементе-контейнере. В компоненте записи должны рендериться все элементы записи.

2017-05-27 11:54 UTC, tbilous commented on components/ui/BlogItem.js
> +  DOM.ul(
Мне просто очень понравился "Segment" из видео и не смог воздержатся, что-бы его не всунуть. Очень удобно иметь несколько  врапперов с набором готовых стилей и выбирать из них. Ну и засунул как умел.  Сейчас закончу работать переделаю и уберу.
Спасибо за замечание

2017-05-27 16:23 UTC, index01d reviewed
похоже, что я все еще не был понят. Давай так: Напиши пожалуйста за что отвечают компоненты BlogList и BlogItem, какую задачу они решают и что должно быть в них имплементировано?

2017-05-27 16:25 UTC, index01d commented
стоп машина, извиняюсь, гитхаб наплужил и показал не тот дифф. Все окей

2017-05-27 16:59 UTC, index01d approved these changes

2017-05-28 05:43 UTC, merged